### PR TITLE
Welding bug fix

### LINKED ISSUE #307: Welding the doors
I accidentally found that after I weld the door I cannot undo it.

### PR DESCRIPTION
**Pull request by shelltitan**
#307

### CODE REVIEW

File: Sources/core/objects/Door.h [hunk 1]
```diff
@@ -10,19 +10,19 @@ class Door: public IOnMapObject
...
+    };
+
     virtual void Open();
     virtual void Close();
     virtual void Process() override;
     virtual void Bump(IdPtr<IMovable> item) override;
     virtual void AttackBy(IdPtr<Item> item) override;
-    bool IsOpen() const { return door_state_ == OPEN; }
-    bool IsClosed() const { return door_state_ == CLOSED; }
+    bool CheckState(STATE state) { return state == door_state_ ; };
```
Comment (kremius) [inline Sources/core/objects/Door.h]: It is better to name new function `IsState` because the function is simple and does not change internal state. `CheckSomething` assumes that something complicated can happen inside.
Also, it should be `const` function (like `IsOpen` or `IsClosed` before).

File: Sources/core/objects/Door.h [hunk 2]
```diff
@@ -76,17 +76,18 @@ class GlassDoor: public IMovable
...
+        OPEN, CLOSED, OPENING, CLOSING  
+    };
+
     virtual void Open();
     virtual void Close();
     virtual void Process() override;
     virtual void Bump(IdPtr<IMovable> item) override;
     virtual void AttackBy(IdPtr<Item> item) override;
-    bool IsOpen() const { return door_state_ == OPEN; }
+    bool CheckState(STATE state) { return state == door_state_; };
```
Comment (kremius) [inline Sources/core/objects/Door.h]: Same here.

File: Sources/core/objects/Door.cpp [hunk 3]
```diff
@@ -117,19 +117,19 @@ void Door::AttackBy(IdPtr<Item> item)
 {
     if (IdPtr<Weldingtool> w = item)
```
Comment (kremius) [inline Sources/core/objects/Door.cpp]: This file is quite old, so codestyle here is not perfect. It will be nice at the same time with bugfix to fix short variables names here in `if` blocks. For example, here it will be better to name it `welder`. There are a couple more such places in the file.
